# Site settings
title: Covid-19
subtitle: OEG-UPM CORD 19
email:
description: Aplicando técnicas de Inteligencia Artificial sobre el conjunto de artículos científicos relacionados con el COVID-19
baseurl: ""
#url: "" # the base hostname & protocol for your site
#author:
#street_address:
#city:
#state:
#zip_code:
#country:
#phone:


# Build settings
markdown: kramdown
